// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//   apiKey: "AIzaSyDa24P4797D156EU3kuf9wb4oPXMNUq_m8",
//   authDomain: "fir-239e0.firebaseapp.com",
//   projectId: "fir-239e0",
//   storageBucket: "fir-239e0.appspot.com",
//   messagingSenderId: "992696514201",
//   appId: "1:992696514201:web:5f5f9a26d4e7e46d766a08",
//   measurementId: "G-J14K4PBKE1"
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAiaW1c9btdDaIQQm_R7tHPVOyn0m44AqU',
//     appId: '1:632534901534:android:f790596508b1809f511f0f',
//     messagingSenderId: '632534901534',
//     projectId: 'secondsem-1cb59',
//     storageBucket: 'secondsem-1cb59.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBTzw1v59JiOhPPnTqIlF-in8Lx7xfMOCs',
//     appId: '1:632534901534:ios:a806a65017583568511f0f',
//     messagingSenderId: '632534901534',
//     projectId: 'secondsem-1cb59',
//     storageBucket: 'secondsem-1cb59.appspot.com',
//     iosBundleId: 'com.example.secondsemflut',
//   );
// }
